language: python
python: 3.6
sudo: required
before_install:
- echo "${GITHUB_TOKEN}" | md5sum
- openssl aes-256-cbc -K $encrypted_f88f8c86b39c_key -iv $encrypted_f88f8c86b39c_iv -in priv_key.txt.enc -out priv_key.txt -d
- sudo apt-get install gnupg
- gpg --import priv_key.txt
- git config --global gpg.program gpg
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- echo "lolmate" >> trash
- git add trash
- git commit -S -m 'travis commit'
- git remote remove origin
- git remote add origin "https://${GITHUB_TOKEN}@github.com/frosty00/travis-test.git"
- git push -v origin HEAD:master
